name: password_manager
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-139.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.26.0
  dartz: ^0.10.1
  flutter_spinkit: ^5.1.0
  sizer: ^2.0.15
  envied: ^0.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  envied_generator: ^0.3.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0


flutter:

  uses-material-design: true
